# Câu 1:
- Tạo ma trận A(4x5) chứa các giá trị ngẫu nhiên 1 -10
- Phân tích thành các thành phần P, L, U. In kết quả.
- Tạo ma trận B từ các thành phần P, L, U.

In [42]:
import numpy as np
import scipy
from scipy.linalg import lu
import HelperLIB.lib_matrix as lib

In [43]:
A = lib.create_matrix_random(4, 5, 1, 10)
A

array([[ 1.,  4.,  5.,  7.,  3.],
       [ 7.,  5.,  7.,  7., 10.],
       [10.,  6.,  1.,  3.,  3.],
       [ 9., 10.,  7.,  4.,  4.]])

In [49]:
lu??

In [44]:
P, L, U = lu(A)


In [45]:
P

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [46]:
L

array([[1.        , 0.        , 0.        , 0.        ],
       [0.9       , 1.        , 0.        , 0.        ],
       [0.7       , 0.17391304, 1.        , 0.        ],
       [0.1       , 0.73913043, 0.0746888 , 1.        ]])

In [47]:
U

array([[10.        ,  6.        ,  1.        ,  3.        ,  3.        ],
       [ 0.        ,  4.6       ,  6.1       ,  1.3       ,  1.3       ],
       [ 0.        ,  0.        ,  5.23913043,  4.67391304,  7.67391304],
       [ 0.        ,  0.        ,  0.        ,  5.39004149,  1.1659751 ]])

In [48]:
B = P.dot(L).dot(U)
B

array([[ 1.,  4.,  5.,  7.,  3.],
       [ 7.,  5.,  7.,  7., 10.],
       [10.,  6.,  1.,  3.,  3.],
       [ 9., 10.,  7.,  4.,  4.]])

# Câu 2: Hãy dùng LU Decomposition để làm lại bài toán này
- Cho 

2a + b + c = 4

a + 3b + 2c = 5

a = 6
- Quy về Ax = B, sau đó giải tìm x.
- Phân tích thành các thành phần P, L, U từ A. In kết quả.
- Tạo A_new từ các thành phần P, L, U.


In [50]:
import scipy.linalg as linalg

In [51]:
A  = np.array([[2,1,1], [1,3,2],[1,0,0]])

In [52]:
B = np.array([4,5,6])
B

array([4, 5, 6])

In [53]:
LU =linalg.lu_factor(A)
LU

(array([[ 2. ,  1. ,  1. ],
        [ 0.5,  2.5,  1.5],
        [ 0.5, -0.2, -0.2]]), array([0, 1, 2], dtype=int32))

In [54]:
#solve given LU and B
x = linalg.lu_solve(LU, B)
print("Solutions(a, b, c):\n",x)

Solutions(a, b, c):
 [  6.  15. -23.]


In [55]:
P, L, U = scipy.linalg.lu(A)

In [56]:
P

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
L

array([[ 1. ,  0. ,  0. ],
       [ 0.5,  1. ,  0. ],
       [ 0.5, -0.2,  1. ]])

In [58]:
U

array([[ 2. ,  1. ,  1. ],
       [ 0. ,  2.5,  1.5],
       [ 0. ,  0. , -0.2]])

In [59]:
B = P.dot(L).dot(U)
B

array([[ 2.00000000e+00,  1.00000000e+00,  1.00000000e+00],
       [ 1.00000000e+00,  3.00000000e+00,  2.00000000e+00],
       [ 1.00000000e+00, -2.77555756e-17,  2.77555756e-17]])

# Câu 3:
- Tạo ma trận C(4x4) chứa các giá trị ngẩu nhiên trong khoảng 5 đến 10.
- Phân tích thành các thành phần Q, R. In kết quả.
- Tái tạo ma trận D từ các thành phần Q, R.


In [60]:
C = lib.create_matrix_random(4,4, 5, 10)
C

array([[ 5.,  7.,  7.,  5.],
       [ 7.,  5.,  5.,  5.],
       [10.,  7., 10.,  8.],
       [10.,  9.,  7., 10.]])

In [61]:
from numpy.linalg import qr

In [62]:
Q, R = qr(C, 'complete')

In [63]:
Q

array([[-0.30206105,  0.84764701, -0.38005281, -0.21404096],
       [-0.42288547, -0.26488969,  0.21771657, -0.83880917],
       [-0.60412209, -0.42161609, -0.61658178,  0.27767476],
       [-0.60412209,  0.18321537,  0.65420659,  0.41651214]])

In [64]:
R

array([[-16.55294536, -13.89480815, -14.49893024, -14.49893024],
       [  0.        ,   3.3067063 ,   1.67542729,   1.37301156],
       [  0.        ,   0.        ,  -3.15815853,   0.79773043],
       [  0.        ,   0.        ,   0.        ,   1.12226883]])

In [66]:
D = Q.dot(R)
D

array([[ 5.,  7.,  7.,  5.],
       [ 7.,  5.,  5.,  5.],
       [10.,  7., 10.,  8.],
       [10.,  9.,  7., 10.]])

# Câu 4:
- Tạo ma trận E(3x3) vuông chứa các giá trị ngẫu nhiên trong khoảng 3 đến 9.
- Từ đó chuyển E thành ma trận vuông đối xứng theo tam giác dưới đường chéo chính.
- Kiểm tra nếu mọi thành phần điều không âm  thì:
    - Phân tích thành L. In kết quả
    - Tái tạo ma trận F từ các thành phần L, L.T.
    
- Ngược lại thì thông báo E có thành phần âm
- Chú ý: dùng np.linalg.eigvalsh(E) để kiểm tra mọi thành phần có âm hay không.
- Mở rộng: thực hiện việc tạo ma trận vuông đối xứng với mọi thành phần đều không âm và phân tích.


In [96]:
E = lib.create_matrix_random(3,3, 3, 9)
E

array([[6., 6., 5.],
       [5., 8., 8.],
       [4., 5., 8.]])

In [84]:
E.shape[0]

3

In [97]:
for i in range(E.shape[0]):
    for j in range(i):
        E[j][i] = E[i][j]

In [90]:
E

array([[3., 6., 8.],
       [6., 8., 7.],
       [8., 7., 3.]])

In [73]:
# Chú ý: có 1 thành phần bị âm nên sẽ không tạo được L
# Kiểm tra mọi thành phần đều dương thì tạo L

In [98]:
test = np.linalg.eigvalsh(E)
test

array([ 1.89816556,  3.32949276, 16.77234168])

In [101]:
flag = np.all(test > 0)
flag

True

In [102]:
from numpy.linalg import cholesky
if flag == True:
    L = cholesky(E)
    print(L)
    F = L.dot(L.T)
else:
    print("E not positive definite")

[[2.44948974 0.         0.        ]
 [2.04124145 1.95789002 0.        ]
 [1.63299316 0.85125653 2.14678729]]


In [104]:
def create_matrix_positive_definite(m, n, start, end):
    E = None
    flag = False
    while flag == False:
        E = lib.create_matrix_random(m, n, start, end)
        for i in range(E.shape[0]):
            for j in range(i):
                E[j][i] = E[i][j]
        test = np.linalg.eigvalsh(E)
        flag = np.all(test >0)
    return E

In [105]:
E = create_matrix_positive_definite(3,3,5,10)
E

array([[10.,  5.,  9.],
       [ 5., 10.,  5.],
       [ 9.,  5.,  9.]])

In [106]:
L = cholesky(E)
print(L)

[[3.16227766 0.         0.        ]
 [1.58113883 2.73861279 0.        ]
 [2.84604989 0.18257419 0.93094934]]


In [108]:
L.T

array([[3.16227766, 1.58113883, 2.84604989],
       [0.        , 2.73861279, 0.18257419],
       [0.        , 0.        , 0.93094934]])

In [107]:
F = L.dot(L.T)
F

array([[10.,  5.,  9.],
       [ 5., 10.,  5.],
       [ 9.,  5.,  9.]])