# Câu 1:
- Tạo ma trận A(5x5) với các giá trị ngẫu nhiên từ 1 đến 10
- Phân tích thành eiganvalues và eiganvectors
- Xác nhận eigenvector đầu tiên theo dot và theo eigenvalues có bằng nhau không?
- Nếu bằng nhau thì tái cấu trúc A từ các eigenvector và eigenvalue

In [2]:
import numpy as np
from numpy.linalg import eig, inv
from numpy import diag
import HelperLIB.lib_matrix as lib

In [3]:
A = lib.create_matrix_random(5,5,1,10)
A

array([[ 1.,  9., 10.,  2.,  7.],
       [ 2.,  7.,  3.,  4.,  4.],
       [ 4.,  1.,  2.,  9.,  5.],
       [ 6.,  4.,  5.,  1.,  3.],
       [ 1.,  3.,  7.,  4.,  8.]])

In [4]:
values, vectors = eig(A)

In [5]:
values

array([21.95040495+0.j        , -4.44135201+3.38634115j,
       -4.44135201-3.38634115j,  1.72779705+0.j        ,
        4.20450202+0.j        ])

In [6]:
vectors

array([[-0.5566055 +0.j        ,  0.67336926+0.j        ,
         0.67336926-0.j        ,  0.0478261 +0.j        ,
        -0.1414961 +0.j        ],
       [-0.38650495+0.j        , -0.03426504+0.04380147j,
        -0.03426504-0.04380147j,  0.01037578+0.j        ,
        -0.60042681+0.j        ],
       [-0.42359136+0.j        , -0.48900842+0.22254456j,
        -0.48900842-0.22254456j,  0.46524161+0.j        ,
         0.03304166+0.j        ],
       [-0.39871664+0.j        , -0.17948662-0.38180503j,
        -0.17948662+0.38180503j,  0.40107   +0.j        ,
        -0.27217433+0.j        ],
       [-0.44988847+0.j        ,  0.27048624+0.06060133j,
         0.27048624-0.06060133j, -0.78759006+0.j        ,
         0.73776411+0.j        ]])

In [7]:
# confirm first eigenvector
B = A.dot(vectors[:, 0])
B

array([-12.21771623+0.j,  -8.48394019+0.j,  -9.2980018 +0.j,
        -8.75199168+0.j,  -9.87523421+0.j])

In [8]:
C = vectors[:, 0] * values[0]
C

array([-12.21771623+0.j,  -8.48394019+0.j,  -9.2980018 +0.j,
        -8.75199168+0.j,  -9.87523421+0.j])

In [10]:
# B == C
#Tái cấu trúc A
Q = vectors
R = inv(Q)
L = diag(values)

In [11]:
Q

array([[-0.5566055 +0.j        ,  0.67336926+0.j        ,
         0.67336926-0.j        ,  0.0478261 +0.j        ,
        -0.1414961 +0.j        ],
       [-0.38650495+0.j        , -0.03426504+0.04380147j,
        -0.03426504-0.04380147j,  0.01037578+0.j        ,
        -0.60042681+0.j        ],
       [-0.42359136+0.j        , -0.48900842+0.22254456j,
        -0.48900842-0.22254456j,  0.46524161+0.j        ,
         0.03304166+0.j        ],
       [-0.39871664+0.j        , -0.17948662-0.38180503j,
        -0.17948662+0.38180503j,  0.40107   +0.j        ,
        -0.27217433+0.j        ],
       [-0.44988847+0.j        ,  0.27048624+0.06060133j,
         0.27048624-0.06060133j, -0.78759006+0.j        ,
         0.73776411+0.j        ]])

In [12]:
R

array([[-0.30017633-0.00000000e+00j, -0.45032124-4.98657943e-17j,
        -0.52982273-0.00000000e+00j, -0.45039797-0.00000000e+00j,
        -0.56649444-0.00000000e+00j],
       [ 0.60850562-2.21123890e-01j, -0.28494857-2.40864203e-01j,
        -0.19519636-5.64609511e-01j, -0.17352288+9.76168384e-01j,
        -0.17047245+1.46976677e-01j],
       [ 0.60850562+2.21123890e-01j, -0.28494857+2.40864203e-01j,
        -0.19519636+5.64609511e-01j, -0.17352288-9.76168384e-01j,
        -0.17047245-1.46976677e-01j],
       [ 0.78229107+2.76001626e-17j, -1.14515217+2.29944742e-18j,
         0.68404706+2.04104878e-17j,  0.14697055-6.20111352e-17j,
        -0.75835808-1.44517999e-17j],
       [ 0.16955718+9.59390043e-18j, -1.32772635-2.98303442e-18j,
         0.45753271+1.02794963e-18j,  0.16984969-2.26664299e-17j,
         0.34957009-6.47851459e-18j]])

In [13]:
L

array([[21.95040495+0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ],
       [ 0.        +0.j        , -4.44135201+3.38634115j,
         0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ],
       [ 0.        +0.j        ,  0.        +0.j        ,
        -4.44135201-3.38634115j,  0.        +0.j        ,
         0.        +0.j        ],
       [ 0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  1.72779705+0.j        ,
         0.        +0.j        ],
       [ 0.        +0.j        ,  0.        +0.j        ,
         0.        +0.j        ,  0.        +0.j        ,
         4.20450202+0.j        ]])

In [14]:
A_new = Q.dot(L).dot(R)
A_new

array([[ 1.-1.61040380e-16j,  9.+3.89149863e-16j, 10.-4.63288373e-16j,
         2.+2.97219545e-16j,  7.+1.35608016e-16j],
       [ 2.+3.17883206e-18j,  7.+4.60898268e-16j,  3.+6.90093367e-17j,
         4.-2.16121235e-17j,  4.+1.57437501e-18j],
       [ 4.+2.86201589e-16j,  1.+6.82596279e-16j,  2.+6.38536184e-16j,
         9.-4.80596506e-16j,  5.-1.66554183e-16j],
       [ 6.-4.99636304e-17j,  4.+2.87496408e-16j,  5.-1.87878058e-16j,
         1.+3.55653082e-16j,  3.+7.27551801e-17j],
       [ 1.-7.20602607e-17j,  3.+4.51923493e-16j,  7.-1.79321306e-16j,
         4.+1.27906382e-17j,  8.+4.47456430e-17j]])

# Câu 2:
- Tạo ma trận P(4x4) vuông với các giá trị ngẫu nhiên từ 1 đến 9
- Tạo ma trận đối xứng S = $P.P^T$
- Tìm eigenvalues và eigenvectors của S.

In [16]:
import numpy as np
from numpy.linalg import eig, inv
from numpy import diag

In [20]:
n = 4
P = np.random.randint(1,10,(n,n))
print(p)

[[9 3 9 1]
 [9 2 9 3]
 [3 3 3 2]
 [1 8 5 4]]


In [23]:
S = P@P.T
S

array([[164, 110, 107,  78],
       [110,  84,  88,  60],
       [107,  88, 117,  44],
       [ 78,  60,  44,  76]])

In [24]:
values, vectors = eig(S)

In [25]:
values

array([369.31120059,   1.50709542,  21.17629135,  49.00541264])

In [26]:
vectors

array([[ 0.64225746,  0.25306278,  0.71150014,  0.13127126],
       [ 0.472823  , -0.87373449, -0.11257796, -0.01877929],
       [ 0.49692861,  0.34082426, -0.44792871, -0.6605003 ],
       [ 0.34206099,  0.23745758, -0.52957873,  0.7390227 ]])