# Câu 1: Tính toán
- Tạo 1 ma trận A(3000, 3) có các giá trị ngẫu nhiên từ 1 đến 255.
- Áp dụng tính toán PCA
- Trực quan hóa kết quả

In [1]:
import numpy as np

In [2]:
A = np.random.randint(1, 256, (3000,3))
A.shape

(3000, 3)

In [3]:
A[0:10]

array([[ 48, 154, 167],
       [183, 169, 214],
       [  3,  12,  15],
       [230, 242, 209],
       [148, 186,  30],
       [227, 179, 133],
       [ 56,   3, 237],
       [ 55, 211, 158],
       [ 97,  42, 191],
       [133, 167, 126]])

In [4]:
#Columns' means
M = np.mean(A.T, axis = 1)
M

array([128.72533333, 130.028     , 128.37666667])

In [5]:
#Center columns by subtracting columns means
C = A - M
C[:10]

array([[ -80.72533333,   23.972     ,   38.62333333],
       [  54.27466667,   38.972     ,   85.62333333],
       [-125.72533333, -118.028     , -113.37666667],
       [ 101.27466667,  111.972     ,   80.62333333],
       [  19.27466667,   55.972     ,  -98.37666667],
       [  98.27466667,   48.972     ,    4.62333333],
       [ -72.72533333, -127.028     ,  108.62333333],
       [ -73.72533333,   80.972     ,   29.62333333],
       [ -31.72533333,  -88.028     ,   62.62333333],
       [   4.27466667,   36.972     ,   -2.37666667]])

In [7]:
#calculate covariance matrix of centered matrix
V = np.cov(C.T)
V[:10]

array([[5437.4937228 ,  152.66858019,  103.54964099],
       [ 152.66858019, 5241.89651484,  -77.50804935],
       [ 103.54964099,  -77.50804935, 5425.35657441]])

In [8]:
#factorize covariance matrix
values, vectors = np.linalg.eig(V)
values

array([5113.01563399, 5552.34762585, 5439.3835522 ])

In [9]:
vectors

array([[ 0.48872312, -0.82057303, -0.29632686],
       [-0.79501349, -0.2789906 , -0.53862585],
       [-0.35930944, -0.49882275,  0.78871578]])

In [10]:
#project data
P = vectors.T.dot(C.T)
P[:10]

array([[-72.38812809, -35.22325301,  73.12628109, ...,  82.53977002,
         75.14523139, -30.57259136],
       [ 40.28687161, -98.12001653, 192.6503819 , ..., -72.27200109,
        -37.42018543, -53.06628274],
       [ 41.47197839,  30.45810633,  11.4067584 , ...,  58.61393174,
         84.89456613,  28.10599693]])