# Câu 1:
- Viết function cal_matrices(op, m1, m2) với op là một trong các toán tử +, -, *, /; m1 và m2 là ma trận(numpy array).
Hãy thực hiện việc tính toán theo toán tử và 2 ma trận truyền vào.\
- Gọi function này với các toán tử khác nhau để xem kết quả

# Câu 2:
- Cho ma trận A =[[1,3,4], [4,5,6], [7,8,9]] và ma trận B =[[2,3],[6,8], [5, 7]]
- Thực hiện dot product cho A.B bằng dot, @

In [2]:
import numpy as np

In [17]:
def cal_matrices(op, m1, m2):
    result = None
    if op == "+":
        result = m1 + m2
    elif op == "-":
        result = m1 - m2
    elif op == "*":
        result = m1 * m2
    elif op == "/":
        result = m1 / m2
    elif op == "dot":
        result = m1.dot(m2)
    elif op == "@":
        result = m1@m2
    else:
        result = None
    return result        

In [4]:
m1 = np.array([[1,3,2,4], [4,3,6,8], [5,6,3,1]])
m2 = np.array([[2,4,5,1], [5,1,2,3], [1,8,1,9]])

In [6]:
print("+")
print(cal_matrices("+", m1, m2))

+
[[ 3  7  7  5]
 [ 9  4  8 11]
 [ 6 14  4 10]]


In [7]:
print("-")
print(cal_matrices("-", m1, m2))

-
[[-1 -1 -3  3]
 [-1  2  4  5]
 [ 4 -2  2 -8]]


In [8]:
print("*")
print(cal_matrices("*", m1, m2))

*
[[ 2 12 10  4]
 [20  3 12 24]
 [ 5 48  3  9]]


In [12]:
print("/")
print(cal_matrices("/", m1, m2))

/
[[0.5        0.75       0.4        4.        ]
 [0.8        3.         3.         2.66666667]
 [5.         0.75       3.         0.11111111]]


In [18]:
print("@")
print(cal_matrices("@", m1, m2))

@


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [10]:
print("None")
print(cal_matrices("No", m1, m2))

None
None


In [19]:
A = np.matrix([[1, 3, 3], [4, 5, 6], [7, 8, 9]])
B = np.matrix( [[2, 3], [6, 8], [5, 7]])
print("Dot")
print(cal_matrices("dot", A, B))

None
[[ 35  48]
 [ 68  94]
 [107 148]]


In [20]:
print("@")
print(cal_matrices("@", A, B))

@
[[ 35  48]
 [ 68  94]
 [107 148]]
