# Câu 1: 
- Viết function cal_scalar_mult(v, b), v là vector hoặc ma trận(numpy array) và b là scalar.
Hãy thực hiện tính toán theo vector hoặc  ma trận và scalar được truyền vào.
Kết quả trả về là 1 vector/matrix tương ứng.
- Gọi function này với các vector/ma trận và scalar khác nhau để xem kết quả.

In [1]:
import numpy as np

In [2]:
def cal_scalar_mult(v, b):
    return v*b;

In [3]:
A = np.matrix([[4,5,2], [5,1,6]])

In [4]:
cal_scalar_mult(A, 5)

matrix([[20, 25, 10],
        [25,  5, 30]])

In [5]:
v = np.array([1,2,3,4])
cal_scalar_mult(v, 2)

array([2, 4, 6, 8])

# Câu 2:
- Hãy viết functioon cho phép người dùng nhập vào 1 ma trận[m,n]
- Hãy viết function cho phéo người dùng nhập vào 1 vector[n].
- Thực hiện phép nhân ma trận với vector trên.

In [6]:
import lib_matrix as lib

In [7]:
A = lib.create_matrix(2,3)

M[1,1]:1
M[1,2]:2
M[1,3]:3
M[2,1]:4
M[2,2]:5
M[2,3]:6


In [8]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
v = lib.create_vector(3)

v[1]:1
v[2]:2
v[3]:3


In [10]:
v

array([1, 2, 3])

In [11]:
cal_scalar_mult(A, v)

array([[ 1,  4,  9],
       [ 4, 10, 18]])

# Câu 3:
- Tương tự câu 2 nhưng các function tạo ma trận và vector thay vì nhập tay thì tự động tạo với 1 giá trị ngẫu nhiên trong khoảng từ start đến end.

In [12]:
import lib_matrix as lib

In [13]:
A = lib.create_matrix_random(2,3, 1, 20)

In [14]:
A

array([[16., 10.,  8.],
       [17., 14., 18.]])

In [15]:
v = lib.create_vector_random(3, 8,25)
v

array([24., 13., 18.])

In [16]:
cal_scalar_mult(A,v)

array([[384., 130., 144.],
       [408., 182., 324.]])

In [17]:
A.dot(v)

array([658., 914.])

# Câu 4:
- Tạo matrix(3x4) có giá trị trong khoảng 0-11
- Tìm ma trận chuyển vị của matrix X
- Tính $X^T$X

In [18]:
B = lib.create_matrix_random(3,4, 0,11)
B

array([[ 1.,  4.,  9., 10.],
       [ 1.,  2.,  8.,  6.],
       [11.,  6., 11.,  0.]])

In [19]:
B_T = B.transpose()
B_T

array([[ 1.,  1., 11.],
       [ 4.,  2.,  6.],
       [ 9.,  8., 11.],
       [10.,  6.,  0.]])

In [20]:
B_T.dot(B)

array([[123.,  72., 138.,  16.],
       [ 72.,  56., 118.,  52.],
       [138., 118., 266., 138.],
       [ 16.,  52., 138., 136.]])

In [21]:
# cách 2:
X = np.arange(12).reshape((3,4))
X


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Câu 5:
- Tạo ma trận A(2,2) với các giá trị số ngẫu nhiên từ 1 đến 4
- Tạo ma trận nghịch đảo B từ ma trận A
- Tìm I

In [22]:
A = lib.create_matrix_random(2,2, 1,4)
A

array([[3., 3.],
       [4., 2.]])

In [23]:
from numpy.linalg import inv

In [24]:
B = inv(A)
B

array([[-0.33333333,  0.5       ],
       [ 0.66666667, -0.5       ]])

In [25]:
I = A.dot(B)
I

array([[1., 0.],
       [0., 1.]])

# Câu 6:
- Tạo ma trận C(5,5) với các giá trị số ngẫu nhiên từ 5 đến 10
- Tính tổng các phần tử trên đường chéo chính(trace)
- Tính định thức (determinat) của C
- Tính hạng (rank) của ma trận C

In [26]:
C = lib.create_matrix_random(5,5, 5,10)
C

array([[ 6.,  6.,  6.,  9.,  5.],
       [ 8., 10.,  6.,  9.,  9.],
       [ 5.,  9., 10.,  6., 10.],
       [ 6., 10.,  8.,  5.,  6.],
       [ 8., 10.,  6.,  8.,  7.]])

In [27]:
from numpy.linalg import det
from numpy.linalg import matrix_rank

In [28]:
traceC = np.trace(C)
traceC

38.0

In [29]:
detC = det(C)
detC

-263.99999999999994

In [30]:
matrix_rank(C)

5

# Câu 7:
- Cho Ax = b
- Tạo ma trận A(3x3) với các giá trị ngẫu nhiên từ 1 đến 6
- Tạo vector b với 3 giá trị ngẫu nhiên từ 1 đến 3.
- Tìm vector x của Ax = b

In [31]:
A = lib.create_matrix_random(3,3, 1,6)
A

array([[6., 6., 6.],
       [6., 1., 4.],
       [3., 4., 3.]])

In [32]:
b = lib.create_vector_random(3,1,3)
b

array([4., 1., 3.])

In [33]:
A_1 = inv(A)
A_1

array([[-1.08333333e+00,  5.00000000e-01,  1.50000000e+00],
       [-5.00000000e-01,  4.44089210e-17,  1.00000000e+00],
       [ 1.75000000e+00, -5.00000000e-01, -2.50000000e+00]])

In [34]:
x = A_1.dot(b)
x

array([ 0.66666667,  1.        , -1.        ])